services:
  - type: web
    name: temporal-app
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    port: 10000
    envVars:
      - key: PORT
        value: "10000"
      - key: TEMPORAL_ADDRESS
        value: "0.0.0.0:7233"
      - key: PYTHONUNBUFFERED
        value: "1"
    buildCommand: echo "Building with Docker"
    healthCheckPath: /